### ISSUE TITLE
Bug: Update LiveSelect to 1.0 to support multiple recipients in DMs

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#493]
ATM when upgrading to 1.0  I got this error:

```
== Compilation error in file lib/phoenix_component.ex ==
** (CompileError) lib/phoenix_component.ex:2266: Phoenix.HTML.FormField.__struct__/0 is undefined, cannot expand struct Phoenix.HTML.FormField. Make sure the struct name is correct. If the struct name exists and is correct but it still cannot be found, you likely have cyclic module usage in your code
    expanding struct: Phoenix.HTML.FormField.__struct__/0
    lib/phoenix_component.ex:2266: Phoenix.Component.inputs_for/1
    expanding macro: Phoenix.Component.Declarative.__pattern__!/2
    lib/phoenix_component.ex:2266: Phoenix.Component.inputs_for/1
```

**Comment by mayel** [comment]
LiveSelect?

**Comment by ivanminutillo** [comment]
> LiveSelect?

oh fixed typo thanks

**Comment by mayel** [comment]
ah they've made some major changes which we need to adapt to: https://github.com/maxmarcon/live_select/blob/main/CHANGELOG.md

**Comment by mayel** [comment]
done

**Comment by ivanminutillo** [comment]
DM are broken now tough - cant select users and the composer often disappears without reason

**Comment by mayel** [comment]
Different issue.
